vars:
    authors: Authors

rules:
    - FileExistsChecker:
        requiredFiles:
            - 'project-walker-core3'
    - FileExistsChecker:
        count: 2
        requiredFiles:
            - '%{project_path}/project-walker-core1'
            - '/project-walker-core2'
            - 'interpol.py'
    - FileContainsChecker:
        matches: ['*.py', '*.md']
        contains: ["Copyright %authors"]
