vars:
    authors: Authors

rules:
    FileExistsChecker:
      requiredFiles:
          - '%{project_path}/project-walker-core1'
          - '/project-walker-core2'
          - 'project-walker-core3'
          - 'interpol.py'
    FileContainsChecker:
      matches: '*.py'
      contains: ["Copyright %authors"]
